SELECT A.ANIMAL_ID,A.NAME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE TO_CHAR(B.DATETIME - A.DATETIME) > 0
ORDER BY TO_NUMBER(TO_CHAR(B.DATETIME - A.DATETIME)) DESC
FETCH FIRST 2 ROWS ONLY