SELECT 
A.TITLE, #게시글 제목
A.BOARD_ID, #게시글 ID
B.REPLY_ID, #댓글 ID 
B.WRITER_ID, #댓글 작성자 ID
B.CONTENTS, #댓글 내용
DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE # 댓글 작성일
FROM USED_GOODS_BOARD AS A INNER JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
WHERE SUBSTR(A.CREATED_DATE,1,7) = '2022-10' #2022년 10월에 작성된 게시글
ORDER BY B.CREATED_DATE, A.TITLE #댓글 작성일을 기준으로 오름차순 정렬