SELECT DISTINCT(B.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE TO_CHAR(B.START_DATE,'YYYY-MM') = '2022-10' AND A.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;